#ifndef SIMPLEORM_LIBRARY
#define SIMPLEORM_LIBRARY

#include <QtCore/qglobal.h>

#if defined(SIMPLEORM_LIBRARY)
#define SIMPLEORM_SHARED_EXPORT Q_DECL_EXPORT
#else
#define SIMPLEORM_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SIMPLEORM_LIBRARY
